name: 보통 개발자의 기록
description: 개발, 메모, 일상..
meta_description: "Your New Jekyll Site, Blogging about stuffs"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
domain_name: "https://clang-engineer.github.io"
google_analytics: "G-3438E60K5Q"
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url: "https://clang-engineer.github.io"
author: "zero"

# Disqus config
disqus-shortname: ""

collections:
  wikis:
    output: true
    permalink: /:collection/:path/


github:
  url: https://github.com/clang-engineer
  branch: develop

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

utterances:
  repo: clang-engineer/clang-engineer.github.io
  issue-term: url
  label: Comment
  branch: master
